theme = "hugo-theme-codex" 

# Override these settings with your own
title = "George Honeywood's blog"
languageCode = "en-gb"
baseURL = "https://george.honeywood.org.uk/"
copyright = "content: <a href='https://creativecommons.org/licenses/by-nc-sa/4.0/'>CC BY-NC-SA 4.0</a> &mdash; theme: modified <a href='https://github.com/jakewies/hugo-theme-codex'>codex</a>"

# You must set this to true to enable the commit
# details setting

enableGitInfo = true

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "UA-180792452-1" 

# Optional params
[params]
  heading = "George Honeywood's blog"

  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  # dateFormat = "3:04pm, 02/01/2006"
  dateFormat = "2006-01-02"

  # Display a message at the bottom of a post showing when it was last updated, with what commit
  # Requires project to be in a git repository, and that
  # enableGitInfo = true
  commitInfo = true
  comments = true

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  #twitter = "https://twitter.com/<your handle>"
  github = "https://github.com/GeorgeHoneywood"
  cv = "/cv/"
  email = "mailto:contact@george.honeywood.org.uk"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  # instagram = "https://instagram.com/<your handle>"
  linkedin = "https://linkedin.com/in/GeorgeHoneywood"
  gpg = "/gh-gpg.pub.key"
  rss = "/index.xml"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["GitHub", "Email", "LinkedIn", "CV", "RSS"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

  # sets meta description for search results etc.
  description = "George Honeywood's website about programming & GIS"

  # name mostly used for ld json schema stuffs
  name = "George Honeywood"

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
# [markup]
#   [markup.highlight]
#     codeFences = false
    
#   # Set to false to disallow raw HTML in markdown files
#   [markup.goldmark.renderer]
#       unsafe = true

sectionPagesMenu = "main"

# Controls the navigation
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  title = "Blog"
  url = "/blog/"

[[menu.main]]
  identifier = "cv"
  name = "CV"
  title = "CV"
  url = "/cv/"

# hack to make hugo rebuild when the CV changes
# you still need to refresh the page manually thoughm live-reload doesn't work :(
[module]
  [[module.mounts]]
    source = "cv/georgehoneywood-cv.html"
    target = "assets/georgehoneywood-cv.html"

  [[module.mounts]]
    source = 'assets'
    target = 'assets'