name: deploy

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    env:
      SOURCEHUT_TOKEN: ${{ secrets.SOURCEHUT_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          # need this for git info
          fetch-depth: 0
          # need this as alta-typst is a submodule
          submodules: recursive

      - name: setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          extended: true
          hugo-version: '0.133.0'

      - name: setup Typst
        uses: GeorgeHoneywood/setup-typst@main
        with:
          version: 'latest'

      - name: run the deploy script
        run: ./deploy.sh
