name: deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          # need this for git info
          fetch-depth: 0

      - name: setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13

      - name: run the deploy script
        run: ./deploy
